// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdinApi.Data;

#nullable disable

namespace OdinApi.Migrations
{
    [DbContext(typeof(OdinDbContext))]
    [Migration("20260606065521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OdinApi.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebitoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SateliteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebitoId");

                    b.HasIndex("SateliteId");

                    b.ToTable("Alertas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2026, 6, 5, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1995),
                            DataResolucao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1996),
                            DebitoId = 1,
                            Mensagem = "Aproximação de detrito detectada",
                            SateliteId = 1,
                            Severidade = "MEDIA",
                            Status = "RESOLVIDO"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1999),
                            DebitoId = 2,
                            Mensagem = "Risco iminente de colisão",
                            SateliteId = 2,
                            Severidade = "ALTA",
                            Status = "ATIVO"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(2001),
                            DebitoId = 3,
                            Mensagem = "Alerta crítico - ação imediata necessária",
                            SateliteId = 3,
                            Severidade = "CRITICA",
                            Status = "ATIVO"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2026, 6, 4, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(2003),
                            DataResolucao = new DateTime(2026, 6, 5, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(2004),
                            DebitoId = 4,
                            Mensagem = "Trajetória de colisão confirmada",
                            SateliteId = 4,
                            Severidade = "ALTA",
                            Status = "RESOLVIDO"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2026, 6, 3, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(2006),
                            DebitoId = 5,
                            Mensagem = "Monitoramento de detrito em progresso",
                            SateliteId = 5,
                            Severidade = "BAIXA",
                            Status = "ATIVO"
                        });
                });

            modelBuilder.Entity("OdinApi.Models.Detrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Altitude")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeteccao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperadorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Velocidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.ToTable("Detritos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altitude = 36000m,
                            DataDeteccao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1885),
                            Identificacao = "DEB-001",
                            Latitude = 0m,
                            Longitude = 79.5m,
                            NivelRisco = 45,
                            OperadorId = 1,
                            Velocidade = 3.07m
                        },
                        new
                        {
                            Id = 2,
                            Altitude = 35786m,
                            DataDeteccao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1890),
                            Identificacao = "DEB-002",
                            Latitude = 15.5m,
                            Longitude = 93.5m,
                            NivelRisco = 65,
                            OperadorId = 2,
                            Velocidade = 3.08m
                        },
                        new
                        {
                            Id = 3,
                            Altitude = 800m,
                            DataDeteccao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1893),
                            Identificacao = "DEB-003",
                            Latitude = -10.2m,
                            Longitude = 110.3m,
                            NivelRisco = 85,
                            OperadorId = 3,
                            Velocidade = 7.45m
                        },
                        new
                        {
                            Id = 4,
                            Altitude = 400m,
                            DataDeteccao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1895),
                            Identificacao = "DEB-004",
                            Latitude = 28.5m,
                            Longitude = 77.2m,
                            NivelRisco = 90,
                            OperadorId = 1,
                            Velocidade = 7.82m
                        },
                        new
                        {
                            Id = 5,
                            Altitude = 600m,
                            DataDeteccao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1898),
                            Identificacao = "DEB-005",
                            Latitude = 5.8m,
                            Longitude = 102.7m,
                            NivelRisco = 55,
                            OperadorId = 2,
                            Velocidade = 7.65m
                        });
                });

            modelBuilder.Entity("OdinApi.Models.Manobra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CombustivelConsumido")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SateliteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("SateliteId");

                    b.ToTable("Manobras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CombustivelConsumido = 5m,
                            DataExecucao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1943),
                            DataSolicitacao = new DateTime(2026, 6, 5, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1937),
                            OperadorId = 1,
                            SateliteId = 1,
                            Status = "EXECUTADA",
                            Tipo = "DESVIO"
                        },
                        new
                        {
                            Id = 2,
                            CombustivelConsumido = 3m,
                            DataExecucao = new DateTime(2026, 6, 5, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1954),
                            DataSolicitacao = new DateTime(2026, 6, 4, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1954),
                            OperadorId = 2,
                            SateliteId = 2,
                            Status = "EXECUTADA",
                            Tipo = "ACELERACAO"
                        },
                        new
                        {
                            Id = 3,
                            CombustivelConsumido = 0m,
                            DataSolicitacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1957),
                            OperadorId = 3,
                            SateliteId = 3,
                            Status = "PENDENTE",
                            Tipo = "DESACELERACAO"
                        },
                        new
                        {
                            Id = 4,
                            CombustivelConsumido = 0m,
                            DataSolicitacao = new DateTime(2026, 6, 3, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1958),
                            OperadorId = 1,
                            SateliteId = 4,
                            Status = "CANCELADA",
                            Tipo = "DESVIO"
                        },
                        new
                        {
                            Id = 5,
                            CombustivelConsumido = 4m,
                            DataExecucao = new DateTime(2026, 6, 2, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1961),
                            DataSolicitacao = new DateTime(2026, 6, 1, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1961),
                            OperadorId = 2,
                            SateliteId = 5,
                            Status = "EXECUTADA",
                            Tipo = "ACELERACAO"
                        });
                });

            modelBuilder.Entity("OdinApi.Models.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1503),
                            Email = "marcus@odin.local",
                            NivelAcesso = "ADMIN",
                            Nome = "Marcus Vinícius"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1508),
                            Email = "hebert@odin.local",
                            NivelAcesso = "OPERADOR",
                            Nome = "Hebert Lopes"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1510),
                            Email = "nicolas@odin.local",
                            NivelAcesso = "OPERADOR",
                            Nome = "Nicolas Monteiro"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1512),
                            Email = "ana@odin.local",
                            NivelAcesso = "USUARIO",
                            Nome = "Ana Silva"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2026, 6, 6, 6, 55, 20, 625, DateTimeKind.Utc).AddTicks(1514),
                            Email = "carlos@odin.local",
                            NivelAcesso = "USUARIO",
                            Nome = "Carlos Santos"
                        });
                });

            modelBuilder.Entity("OdinApi.Models.Satelite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CombustivelAtual")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusOperacional")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.ToTable("Satelites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CombustivelAtual = 500m,
                            DataLancamento = new DateTime(2013, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "INSAT-3D",
                            OperadorId = 1,
                            StatusOperacional = "ATIVO"
                        },
                        new
                        {
                            Id = 2,
                            CombustivelAtual = 450m,
                            DataLancamento = new DateTime(2014, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "CBERS-4",
                            OperadorId = 2,
                            StatusOperacional = "ATIVO"
                        },
                        new
                        {
                            Id = 3,
                            CombustivelAtual = 380m,
                            DataLancamento = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Amazonia-1",
                            OperadorId = 3,
                            StatusOperacional = "ATIVO"
                        },
                        new
                        {
                            Id = 4,
                            CombustivelAtual = 420m,
                            DataLancamento = new DateTime(2017, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "SGDC-1",
                            OperadorId = 1,
                            StatusOperacional = "ATIVO"
                        },
                        new
                        {
                            Id = 5,
                            CombustivelAtual = 350m,
                            DataLancamento = new DateTime(1998, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "BRASILSAT-B2",
                            OperadorId = 2,
                            StatusOperacional = "MANUTENCAO"
                        });
                });

            modelBuilder.Entity("OdinApi.Models.Alerta", b =>
                {
                    b.HasOne("OdinApi.Models.Detrito", "Detrito")
                        .WithMany("Alertas")
                        .HasForeignKey("DebitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OdinApi.Models.Satelite", "Satelite")
                        .WithMany("Alertas")
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detrito");

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("OdinApi.Models.Detrito", b =>
                {
                    b.HasOne("OdinApi.Models.Operador", "Operador")
                        .WithMany("Detritos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("OdinApi.Models.Manobra", b =>
                {
                    b.HasOne("OdinApi.Models.Operador", "Operador")
                        .WithMany("Manobras")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdinApi.Models.Satelite", "Satelite")
                        .WithMany("Manobras")
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("OdinApi.Models.Satelite", b =>
                {
                    b.HasOne("OdinApi.Models.Operador", "Operador")
                        .WithMany("Satelites")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("OdinApi.Models.Detrito", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("OdinApi.Models.Operador", b =>
                {
                    b.Navigation("Detritos");

                    b.Navigation("Manobras");

                    b.Navigation("Satelites");
                });

            modelBuilder.Entity("OdinApi.Models.Satelite", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Manobras");
                });
#pragma warning restore 612, 618
        }
    }
}
